### ISSUE TITLE
Idea for the browser branch

### ISSUE THREAD

**Issue by FayneAldan** [smealum/3ds_hb_menu#22]
For each folder, maybe you could have it detect if the folder contains boot.3dsx or \[folder name\].3dsx. If the file exists, then have it act like an app in the master branch, but with the ability to press right to open the folder.

**Comment by FayneAldan** [comment]
I would program this myself, but C is the only well known programming language I don't know. (That and Python... and Ruby... and Perl...)

**Comment by fincs** [comment]
It already works this way IIRC.

**Comment by HandsomeMatt** [comment]
Indeed. It's even in the readme

**Comment by FayneAldan** [comment]
Notice the title. "Idea for the **browser branch**"

**Comment by FayneAldan** [comment]
closing since browser branch was removed

**Comment by fincs** [comment]
Clarification: your proposed idea was actually implemented in the browser branch (without the ability to open the folder), and afterwards the browser branch was merged into master.
