### ISSUE TITLE
Closing & reopening lid of 3ds gives black screen

### ISSUE THREAD

**Issue by phase** [smealum/3ds_hb_menu#25]
The screen will go black when you have the Homebrew Launcher open and you close & reopen your 3DS. The only way to fix it is restarting your system.

**Comment by yellows8** [comment]
Already mentioned here: https://smealum.github.io/ninjhax2/

**Comment by phase** [comment]
@yellows8  But it's still an issue :wink:

**Comment by shinyquagsire23** [comment]
@phase Not an issue with this menu, it's an issue with ninjhax2. Nothing can be fixed in this codebase to remedy this issue.

**Comment by phase** [comment]
@shinyquagsire23 Darn, should I make an issues on that repo?

**Comment by profi200** [comment]
Press the home button once and sleepmode will work. No idea why this works.

**Comment by JeffreyO** [comment]
+profi200 Thanks for the tip, this works.
