### ISSUE TITLE
Argument passing not working with callBootloaderRunTitle_2x()

### ISSUE THREAD

**Issue by suloku** [smealum/3ds_hb_menu#27]
When launching a title under a certain title using the title browser, argument passing won't work as it is supposed to.

With current master, argc is set to 2 for some reason.

Also, adding this code for setting argv[1] won't properly work if the homebrew is boot using the title selector, but will work fine otherwise: https://github.com/smealum/3ds_hb_menu/pull/16

I tried solving this myself, but I was unable to. Even though the uses are limited, I think argument passing from HBL is interesting to define different boot parameteres (which could be added to the xml descriptor for example), but for now the best use would be passing the title ID under which the homebrew is running, for applications like svdt which can benefit from it.

In any case, it is something that's not properly working right now.

**Comment by yellows8** [comment]
" but for now the best use would be passing the title ID under which the homebrew is running, for applications like svdt which can benefit from it." Not implemented in ctrulib atm -> http://3dbrew.org/wiki/APT:GetProgramID (Regarding the actual issue: not really familiar with that myself)

**Comment by suloku** [comment]
Great to know a possible future ctrulib update will solve that certain problem, thank you yellows8.

**Comment by smealum** [comment]
APT:GetProgramID will not work because apps arent launched through APT iirc.

" but for now the best use would be passing the title ID under which the homebrew is running, for applications like svdt which can benefit from it." : this is planned, should be in the next version of payloads

**Comment by suloku** [comment]
Thank you very much for your response, nice to know there are plans regarding this.

I'm still curious about why argument passing fails with callBootloaderRunTitle_2x() but works just fine with callBootloader_2x() though.

**Comment by smealum** [comment]
so actually according to yellows8 APT:GetProgramID  might totally work. give it a shot and let me know if possible please @suloku

**Comment by suloku** [comment]
I tried to implement it into ctrulib, but I'm probably doing something wrong or it's not working (or both):

Result APT_GetProgramID(Handle* handle, u32* pIDlo, u32* pIDhi)
{
	if(!handle)handle=&aptuHandle;

	u32* cmdbuf=getThreadCommandBuffer();
	cmdbuf[0] = 0x00580002; //request header code
	cmdbuf[1] = 0x20;
	
	Result ret=0;
	if((ret=svcSendSyncRequest(*handle)))return ret;

	if(ret==0)ret = cmdbuf[1];

	if(pIDlo)
	{
		*pIDlo = 0;
		if(ret==0)*pIDlo=cmdbuf[2];
	}
	if(pIDhi)
	{
		*pIDhi = 0;
		if(ret==0)*pIDhi=cmdbuf[3];
	}

	return ret;
}

And I'm calling it like this, but both ID remain 0.

	u32 low = 0;
	u32 high = 0;
	
	APT_GetProgramID(NULL, &low, &high);
	printf("%04X\n", low);
	printf("%04X\n", high);

**Comment by yellows8** [comment]
You should really use u64 for that. You have to use aptOpenSession and aptCloseSession too.

**Comment by suloku** [comment]
Oh, calling aptOpenSession and aptCloseSession got it working. That's what you get when you don't know what you are doing.
About using an u64, I just wanted to test if it worked, so I pretty much copy pasted from 3dbrew.

This gets the title ID issue solved, lots of thanks for that, gonna implement it into svdt right away; but the actual issue still remains a mistery.

**Comment by suloku** [comment]
I guess this was fixed with ninhax 2.5 since HANS uses argument passing
