### ISSUE TITLE
9.9 issues with otherapp 2.5 payloads on oot3dhax

### ISSUE THREAD

**Issue by BPSpike** [smealum/3ds_hb_menu#29]
I know this isn't exactly the page to do this, feel free to close this issue whenever, but since this is the next best thing I could fnd, I will put this here:

There seems to be something wrong with the new payloads, not sure if it's an issue with em or the oot3dhax itself, it just crashes to home menu with an unreadable bottom & top screen, which is different to what happens with the 2.1 payloads. I already verified multiple times that they were the correct version, too. Most people are having issues with it, so I don't know if there are any specific versions that do actually work.

Sorry for the bother.

**Comment by yellows8** [comment]
Works fine for me with payload 2.5 + oot3dhax + New3DS v10.1 JPN. Can you upload a pic or something of this?

**Comment by BPSpike** [comment]
Sure thing, sorry for the late answer, had to borrow a decent camera.

This happens in both digital and physical versions, the console itself is an o3DS XL, on 9.9.0-26U.

Firmware version: http://imgur.com/ikTb1yy

2.1 payload works as normal: http://imgur.com/llFt88o

What happens with 2.5: 
http://imgur.com/K8GL5t1
http://imgur.com/T7V2M7r

Crash to home: http://imgur.com/pxvf2N8

The ropbin payload for themehax works as intended, mind you. But the otherapp, at least for my only other option, OOT3D, doesn't seem to work.

**Comment by yellows8** [comment]
Can you dump the payload.bin from your savedata(from the game itself), and calculate the SHA256 hash + check the filesize?

**Comment by BPSpike** [comment]
Sure!
2.5 payload.bin
SHA256: 2a7d09fa99c9b02524c142a33956e778fae570de147f03b7b49596ced7d12e7b
size: 41.1 KB (42,088 bytes)

It compares to POST5_U_20480_usa_9221.bin, which is the one I get manually from selecting 9.9.0-26U on http://smealum.github.io/3ds/, when trying to troubleshoot by myself earlier on.
SHA256: 2a7d09fa99c9b02524c142a33956e778fae570de147f03b7b49596ced7d12e7b
Size: 41.1 KB (42,088 bytes)

**Comment by yellows8** [comment]
That matches the one I just now downloaded as well. Guess this needs debugged at some point....

**Comment by BPSpike** [comment]
Oh well, guess I can deal with using 2.1 from oot3dhax for the moment, and 2.5 from themehax. Shame about the custom themes, but eh, 2.5 features are just too nice to pass on.
Thanks for yer time! :+1:

**Comment by yellows8** [comment]
Just tested on Old3ds v9.9: cubicnin-hax worked, ironhax worked, {stuff which uses otherapp payload} worked. oot3dhax is the only one that failed.

**Comment by BPSpike** [comment]
That's... weird. And it works on 10.1, right? An acquaintance told me it doesn't work on 10.2 either, for that matter, with the 2.5 payloads.

oot3dhax is my only other available entrypoint besides menuhax, now that the browser was blocked via the update nag (this one could be fixed if we had access to the browser saves, right?)

**Comment by yellows8** [comment]
The exact same exception-dump happens with v10.2, I assume v10.1 would be the same. Maybe it only happens with the Old3DS payload....

**Comment by yellows8** [comment]
"(this one could be fixed if we had access to the browser saves, right?)" <- Kind of pointless since modifying that savedata would require hax to begin with.

**Comment by yellows8** [comment]
So, with Old3DS USA v10.2 it crashes, but with New3DS USA v10.2 it works fine. This is with oot3dhax of course. Payload sizes for these two are identical. Guessing it's some sort of icache issue...

**Comment by BPSpike** [comment]
Would that be fixable, or it's related to sofware(oot3D) incompatibility?

**Comment by BPSpike** [comment]
Ok, this is where it gets fun.
The issue seems to be somewhat linked to the pad config of menuhax. For example, if we have it setup to boot while pressing L, if you load up the save and press A in oot3d, as soon as the garbled up text shows up, if you press L and keep it pressed, it will go to a white screen on bottom, and then on the top screen it will show the 2.5 beta payload boot process, followed by the usual flashing colors in the bottom screen.

If we change the pad config in menuhax to other buttons or no-buttons, oot3dhax will follow up these changes, booting the payload when meeting those requirements.
If you don't meet the button/pad requirement, then it crashes to home and asks you to reboot, as usual.

I didn't dare test it without menuhax as it's my only reliable entrypoint when I inject the 2.5 payload in oot3D.

**Comment by yellows8** [comment]
Sounds like you're just triggering menuhax there.

**Comment by profi200** [comment]
If you have both installed and *hax tries to take over home menu it could be that the menuhax payload runs first.

**Comment by BPSpike** [comment]
I found it weird because menuhax never shows the 2.5 payload beta text on the top screen, it goes straight to the debug one, but sounds like what you said, indeed. I'll try getting a friend to lend me his oot3d cartridge in a while, and repeat this with menuhax uninstalled, just in case.

**Comment by yellows8** [comment]
http://3dbrew.org/wiki/Home_Menu#Returning_to_Home_Menu_from_a_crashed_application

**Comment by BPSpike** [comment]
Yeah, my friend  just came over with his oot3dhax with 2.1 payloads, as a backup plan.
I proceeded to uninstall/remove menuhax and repeat the previously mentioned process, it always crashes now, so, yeah, it was indeed just triggering the menuhax payloads.

**Comment by Kojakuu** [comment]
@yellows8 "So, with Old3DS USA v10.2 it crashes, but with New3DS USA v10.2 it works fine. This is with oot3dhax of course. Payload sizes for these two are identical. Guessing it's some sort of icache issue..." So you've managed to get 2.5 payloads working with oot3dhax on 10.2 USA? How exactly is it done?

**Comment by yellows8** [comment]
The *hax payloads needs updated, but none of us have built any payload that actually has the intended change yet successfully.

**Comment by Kojakuu** [comment]
So it's a matter of figuring out what's wrong with the payloads and tweaking them to work for oot3dhax in particular?

**Comment by yellows8** [comment]
In theory having *all* initial otherapp code being located at the start of the payload should fix it.

**Comment by Kojakuu** [comment]
Did you need someone to test that theory? If you can package up the payload, I can test it.

**Comment by yellows8** [comment]
No, the problem is that we haven't figured out how to get the linker-script adjusted properly to get the above result.

**Comment by Kojakuu** [comment]
Ah, I see. Well, should you end up needing someone to test it, then let me know. I'm glad to help if I can.

**Comment by appeater** [comment]
It seems as you are aware of potential issues. I'll just add some info I posted on Phase's repo for OoThax, as well as some new (most likely not relevant?) info.
--
N3DS 9.9.0-26E
After downloading the correct otherapp file from smealum and inserting it to my cartridge with save_manager something changed. Now it doesn't just display gibberish before kicking me to home menu. It gives me a readable top screen which states its hax 2.5, a time stamp, as well as "The homemenu robpin is ready."

After a couple of seconds it closes the game and tells me system needs to reboot.
--
New info:
I downloaded a otherapp file for a O3DS on 9.5.0-xxE. On this device it gives me the same screen "The homemenu robpin is ready", before it successfully boots into HBL.

I'm guessing we play the waiting game until Smea got new versions available? (Just guessing so since i downloaded the otherapp file from his site)

Thank you all for the time and effort you put into this :)

**Comment by yellows8** [comment]
So... Did it work properly on your New3DS or not?(not enough info if the latter)

**Comment by appeater** [comment]
Ok.
I figured I would give it one more go. I downloaded 9.9.0-26E robpin from smealums site, named it payload.bin and with the help of save_manager I put it into my game.
Now OoThax seems to be working! I don't really know what I did differently, as tho I'm pretty sure I had the correct files last time as well.

In short; now working on N3DS 9.0.0-26E :) Sometimes it stops on "Home menu robpin is ready" and a white bottom screen. But it seems to work more times then not :)

**Comment by yellows8** [comment]
https://twitter.com/smealum/status/662007523319287808

**Comment by Kojakuu** [comment]
Wait, so did you update the installer or do we just need to use an offline version and download the otherapp payload ourselves from smealum?

**Comment by yellows8** [comment]
Just install the updated payload.

**Comment by BPSpike** [comment]
Yup, it works on my 9.9.0-26U o3ds now, thanks a lot, Smea and yellows8
