### ISSUE TITLE
EShop throws error code 007 -2404

### ISSUE THREAD

**Issue by MrMonotone** [smealum/3ds_hb_menu#30]
I hope this is an acceptable place to put this. On the latest starter back as of (11/02) 4pm PST, connection to the eshop works perfectly. However well ever I try to download something the error code 007 -2404 is thrown.

**Comment by MrMonotone** [comment]
New 3DS v9.0.2-20U (whatever they shipped on)

**Comment by yellows8** [comment]
Can you be more specific with "try to download something"?

**Comment by MrMonotone** [comment]
@yellows8 When you select download on any software, the error is thrown. I do not know how more specific I can be. Just try to download anything. By download I mean press the download button on any software download screen. For example, I went to download the update for Monster Hunter 4. I loaded up the eshop. I was connected fine. I navigated to the package I wanted to download. Selected the download option. Eshop error 007 - 2404 was thrown. Let me know if I can describe the issue better. I am sure you will encounter it though if you try it out on any firmware below 10.0.

**Comment by MrMonotone** [comment]
Clicking the download button throws the error*

**Comment by yellows8** [comment]
Well others have said just "opening anything" triggered it, so....

**Comment by MrMonotone** [comment]
@yellows8 The behavior changed apparently. As of now I can no longer get to the page. It must have been an internal update. They said the maintenance was done at around 12pm PST. They must have continued later to patch more things.

**Comment by yellows8** [comment]
http://3dbrew.org/wiki/EShop#Server_changes_following_the_November_2.2C_2015.2C_maintenance

**Comment by MrMonotone** [comment]
@yellows8 So this "%s/samurai/ws/%s/title/%llu/other_purchased?shop_id=1&lang=%s&_type=json" was replaced for this "%s/ninja/ws/%s/title/%llu/prepurchase_info?%s=%s&shop_id=1&_type=json" ?
By your description I am assuming that it is trying to request the wrong page when getting the prepurchase information? Would it be possible just to redirect the URL and parse it into the correct output? Maybe my thinking is too simple. I really want a look at HANS haha

**Comment by yellows8** [comment]
"prepurchase" is completely unrelated.

**Comment by MrMonotone** [comment]
@yellows8 So it just looks for that URL and panics because it cant ping it then?

**Comment by yellows8** [comment]
HTTP 404.

https://twitter.com/smealum/status/661427812390211584
