### ISSUE TITLE
If you only have a small amount of screenshots, scr_tool doesn't convert them

### ISSUE THREAD

**Issue by mariomadproductions** [smealum/3ds_hb_menu#33]
it says it is done straight away, without displaying anything on the top screen. the screenshot folder is emtpy when I check it on PC. there is, however, a raw screenshot file, though I do not know the contents, as I don't know how to convert it on PC.

3DS - 9.5.0-22E
menuhax - v2.0
4/11/15 starter pack ver

**Comment by mariomadproductions** [comment]
I haven't really given enough detail.

**Comment by profi200** [comment]
Please don't make multiple issues for every fart. You can sum them up in 1 issue.

**Comment by mariomadproductions** [comment]
Sorry. I'll combine them.
