### ISSUE TITLE
Add ability to close Homebrew Launcher and go to 3ds home menu.

### ISSUE THREAD

**Issue by ofry** [smealum/3ds_hb_menu#42]
Hello.

I have 9.2 firmware on emuNAND and Gateway cards.

I installed CIA version of Homebrew_Launcher Loader from https://github.com/yellows8/hblauncher_loader

And it works! But I want ability to switch between Homebrew Launcher and standard Home Menu 3ds.
If I press "Home" button, then I returned to Homebrew Launcher again :(

So I can return to Home Screen only if I reboot my 3ds.

**Comment by yellows8** [comment]
I thought of trying to implement this in hbmenu somehow before but still never got around to it.

**Comment by fincs** [comment]
This was implemented in hax 2.6 through `hb:kill`.
