### ISSUE TITLE
X: Return to Home Menu FREEZE

### ISSUE THREAD

**Issue by Kidel** [smealum/3ds_hb_menu#53]
Using menuhax with robpin payload on NEW 3DS 10.6.0.31 EUR.
Return to home menu with no reboot just freezes so I have no way to access EShop without updating. 

Edit: solved with downgrade to 9.2.0

**Comment by Kidel** [comment]
On a side note: it used to work just fine, I even downloaded MHGen demo from eshop. Just recently, with no updates at all on 3ds or homebrew, it stopped working.

**Comment by Kidel** [comment]
Solved. No reboot works after downgrading to 9.2.0.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#usage-notes-for-sdiconhax
