### ISSUE TITLE
Yellow lower screen at 11.1.0.34E

### ISSUE THREAD

**Issue by HawkGonzo** [smealum/3ds_hb_menu#55]
I get access to HB with freakyhax, and when I try to lauch Braindump or Rutile Ruby Hack, the lower screen goes through red and other colors to get blocked in yellow. I re-installed all files and revised them, but I don't find any mistake... What should I do?

**Comment by yellows8** [comment]
https://github.com/yellows8/hblauncher_loader/issues/39
