### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by phoen1x74** [smealum/3ds_hb_menu#59]
Trying to add a few tweaks to hblauncher, but I need help compiling it on Ubuntu 16.10. I have devkitpro and devkitarm installed, and zlib installed as well.

**Comment by WinterMute** [comment]
You don't have devkitPro installed, the organisation that produces devkitARM is not something you install.

We need to know what your issue actually is, we're not psychic. What have you done? What errors do you get?

**Comment by phoen1x74** [comment]
Thanks for being a smartass. After exporting devkitarm and devkitpro to my ~/3ds_hb_menu-master folder, then attempting "make," I get `arm-none-eabi-gcc -MMD -MP -MF /home/ben/Documents/3ds/3ds_hb_menu-master/build/titles.d -g -Wall -O2 -mword-relocations -ffunction-sections -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/home/ben/Documents/3ds/3ds_hb_menu-master/include -I/home/ben/devkitPro/portlibs/armv6k/include -I/home/ben/devkitPro/portlibs/3ds/include -I/home/ben/devkitPro/libctru/include -I/home/ben/Documents/3ds/3ds_hb_menu-master/build -DARM11 -D_3DS -DVERSION=\"1.1.1\" -c /home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c -o titles.o 
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c: In function 'loadTitleInfoIcon':
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:50:95: warning: excess elements in scalar initializer
 ileDirectly(&fileHandle, (FS_Archive){ARCHIVE_SAVEDATA_AND_CONTENT, (FS_Path){P
                                                                     ^
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:50:95: note: (near initialization for '(anonymous)')
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:50:189: error: incompatible type for argument 4 of 'FSUSER_OpenFileDirectly'
 0, (u8*)archivePath}}, (FS_Path){PATH_BINARY, 0x14, (u8*)filePath}, FS_OPEN_REA
                                                                     ^
In file included from /home/ben/devkitPro/libctru/include/3ds/services/am.h:7:0,
                 from /home/ben/devkitPro/libctru/include/3ds.h:31,
                 from /home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:5:
/home/ben/devkitPro/libctru/include/3ds/services/fs.h:317:8: note: expected 'FS_Path {aka struct <anonymous>}' but argument is of type 'int'
 Result FSUSER_OpenFileDirectly(Handle* out, FS_ArchiveID archiveId, FS_Path arc
        ^
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:50:15: error: too few arguments to function 'FSUSER_OpenFileDirectly'
  Result ret = FSUSER_OpenFileDirectly(&fileHandle, (FS_Archive){ARCHIVE_SAVEDAT
               ^
In file included from /home/ben/devkitPro/libctru/include/3ds/services/am.h:7:0,
                 from /home/ben/devkitPro/libctru/include/3ds.h:31,
                 from /home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:5:
/home/ben/devkitPro/libctru/include/3ds/services/fs.h:317:8: note: declared here
 Result FSUSER_OpenFileDirectly(Handle* out, FS_ArchiveID archiveId, FS_Path arc
        ^
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c: In function 'populateTitleList':
/home/ben/Documents/3ds/3ds_hb_menu-master/source/titles.c:129:9: warning: implicit declaration of function 'AM_GetTitleIdList' [-Wimplicit-function-declaration]
   ret = AM_GetTitleIdList(tl->mediatype, num, tmp);
         ^
/home/ben/devkitPro/devkitARM/base_rules:84: recipe for target 'titles.o' failed
make[1]: *** [titles.o] Error 1
Makefile:128: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by mtheall** [comment]
Sounds like you need to build and install upstream libctru.

**Comment by phoen1x74** [comment]
I already have it installed and up to date.

**Comment by mtheall** [comment]
but did you install it to ${DEVKITPRO}/libctru or possibly ${CTRULIB}?

**Comment by phoen1x74** [comment]
Yes. `mkdir -p /home/ben/devkitPro/libctru
bzip2 -cd libctru-1.1.0.tar.bz2 | tar -xf - -C /home/ben/devkitPro/libctru
`

**Comment by WinterMute** [comment]
you need to use libctru-upstream branch to compile it with upstream libctru.

**Comment by phoen1x74** [comment]
Can you explain what you mean? Sorry if I'm being obnoxious. I already have the latest from the main branch installed.

**Comment by WinterMute** [comment]
https://github.com/smealum/3ds_hb_menu/tree/libctru-upstream

git checkout libctru-upstream in your clone of 3ds_hb_menu.

**Comment by phoen1x74** [comment]
Got it, thanks!
